### ISSUE TITLE
dist missing config directory by default

### ISSUE THREAD

**Issue by rkben** [SvenBrnn/hazardous-killbot#7]
As the title says. The Docker configuration may sort this out, running outside of Docker this issue occurs.
```
[rkb@lemon src]$ npm run start

> s-connect-metrics-exporter@0.1.0 start
> cd dist && node index

node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir './config'
    at Object.readdirSync (node:fs:1392:3)
    at ZKillSubscriber.loadConfig (/home/rkb/tmp/hazardous-killbot/src/dist/zKillSubscriber.js:480:24)
    at new ZKillSubscriber (/home/rkb/tmp/hazardous-killbot/src/dist/zKillSubscriber.js:99:14)
    at Function.ZKillSubscriber.getInstance (/home/rkb/tmp/hazardous-killbot/src/dist/zKillSubscriber.js:396:29)
    at Object.<anonymous> (/home/rkb/tmp/hazardous-killbot/src/dist/index.js:11:45)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './config'
}
```

**Comment by SvenBrnn** [comment]
Hey,
thanks for your issue, however the bot was never meant to be ran outsite of docker since it is a hassle to deal with x versions of nodejs on x different servers. Docker makes everyone use the same version (at least major) of NodeJS wich will make bugs easyer to find.
If you wish to use the bot outside of docker you are free to, howewer i won't support it. I also only have a limited amount of free time.
Greetings Sven
